### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by keyoti** [sailro/Bdtunnel#8]
In BdtWebServer, line 84 you have 

var xmlConfig = new XMLConfig(ConfigFile, 1);

should be

var xmlConfig = new XmlConfig(ConfigFile, 1);

**Comment by sailro** [comment]
Fixed here https://github.com/sailro/Bdtunnel/commit/d8256504e594c676cf3c6921171c7e61cae50cc4

**Comment by ArashRahimian** [comment]
Thanks a lot. It has many problems and I'm working on block chain parts. Also oidid not published it because some of the banking systems in Iran are under attack. If i complete the process publishing in this framework the hackers could use it for other reasons. Now I'm stop working on it. What should I do? Should I continue?

**Comment by ArashRahimian** [comment]
Sorry about the comment! I'm using mobile phoe and it thought that your comments on my project.
